### ISSUE TITLE
Negar acesso de usuários comuns às páginas de Reports

### ISSUE THREAD

**Issue by augustovictor** [victoraweb/getick-repo#1]
No controller de Reportsé realizada a verificação do usuário armazenado em sessão quando este tenta acessar a página de algum dos reports. Caso não possua o perfil de admin ele é redirecionado para a página inicial do sistema, caso possua, é redirecionado para a página de solicitada.

**Comment by victoraweb** [comment]
Apenas admin acessa paginas de:
- Reports
- Crud eventos
- Crud tickets

**Comment by gleidsonxd** [comment]
done
