### ISSUE TITLE
Comprar ingresso

### ISSUE THREAD

**Issue by augustovictor** [victoraweb/getick-repo#2]
Quando o usuário efetua uma compra, é realizada uma série de operações no controller de compras:
1 - É criada uma nova instância de compra armazenando o id do usuário logado no sistema e o id do ingresso cadastrado para o evento em questão;
2 - O ingresso, já cadastrado em um evento, tem seu campo de 'user_id' atualizado para o id do usuário comprador;
3 - O ingresso comprado deixa de ser exibido nos ingressos disponíveis para o evento;
4 - O nome do usuário passa a constar na lista de pagantes do evento para qual comprou o ingresso.

**Comment by LucianoWanderley** [comment]
Requisito e Caso de Uso 39
