### ISSUE TITLE
Usuarios apenas deletam seus comentarios e admin

### ISSUE THREAD

**Issue by augustovictor** [victoraweb/getick-repo#4]
No controller de Comentários é realizada a verificação do usuário armazenado em sessão quando este tenta  utilizar o método de remoção de comentários Caso não possua o perfil de admin ou o comentário não seja dele próprio,ele é redirecionado para a página inicial do sistema, caso possua, é executada a operação de remoção.

**Comment by LucianoWanderley** [comment]
Fazendo

**Comment by LucianoWanderley** [comment]
Concluido
