### ISSUE TITLE
Negar acesso de usuários comuns às páginas de Manter eventos

### ISSUE THREAD

**Issue by augustovictor** [victoraweb/getick-repo#5]
No controller de Eventos é realizada a verificação do usuário armazenado em sessão quando este tenta acessar a página de criar, editar, atualizar ou o método de remoção de eventos. Caso não possua o perfil de admin ele é redirecionado para a página inicial do sistema, caso possua, é redirecionado para a página de solicitada. Já caso tente acessar a página de listar eventos, não há restrição de acesso por perfil.

**Comment by gleidsonxd** [comment]
done
