### ISSUE TITLE
Negar acesso de usuários comuns às páginas de Manter Usuário

### ISSUE THREAD

**Issue by augustovictor** [victoraweb/getick-repo#7]
No controller de Usuarios é realizada a verificação do usuário armazenado em sessão quando este tenta acessar a página de listar, editar ou o método de remoção de usuário. Caso não possua o perfil de admin ele é redirecionado para a página inicial do sistema, caso possua, é redirecionado para a página de solicitada. Já caso tente acessar a página de cadastrar usuário, login ou logout, não há restrição de acesso por perfil.

**Comment by LucianoWanderley** [comment]
Fazendo
