### ISSUE TITLE
Negar acesso de usuários comuns às páginas de Manter Convidados

### ISSUE THREAD

**Issue by augustovictor** [victoraweb/getick-repo#9]
No controller de Convidados é realizada a verificação do usuário armazenado em sessão quando este tenta acessar a qualquer uma das páginas de manter convidados. Caso não possua o perfil de admin ele é redirecionado para a página inicial do sistema, caso possua, é redirecionado para a página de solicitada.

**Comment by gleidsonxd** [comment]
done
